pipeline {
    agent { label 'agent' }

    stages {
        // Step 1: Checkout repository
        stage('checkout') {
            steps {
                git changelog: false, poll: false, url: 'https://github.com/Vishnu-chaitanya/jenkins.git'
            }
        }

        // Step 2: Unit Testing (Runs on ALL branches)
        stage('test') {
            steps {
                sh '''
                cd javaapp-tomcat
                mvn clean test
                '''
            }
        }

        // Step 3: Package .WAR File (Skipped on Dev, runs on master/main)
        stage('build') {
            when {
                anyOf {
                    branch 'master'
                    branch 'main'
                }
            }
            steps {
                sh '''
                cd javaapp-tomcat
                mvn clean package -DskipTests
                '''
            }
        }

        // Step 4: SonarQube Code Analysis (Skipped on Dev, runs on master/main)
        stage('sonar_analysis') {
            when {
                anyOf {
                    branch 'master'
                    branch 'main'
                }
            }
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                    cd javaapp-tomcat
                    mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                    -Dsonar.projectKey='jenkins-new-test' \
                    -Dsonar.projectName='jenkins-new-test'
                    '''
                }
            }
        }

        // Step 5: SCP & SSH Deployment to Tomcat (Skipped on Dev, runs on master/main)
        stage('deploy') {
            when {
                anyOf {
                    branch 'master'
                    branch 'main'
                }
            }
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'tomcat-credentials', keyFileVariable: 'KEY', usernameVariable: 'USER')]) {
                    sh '''
                    cd javaapp-tomcat/target
                    ls
                    scp -i "$KEY" -o StrictHostKeyChecking=no artisantek-app.war $USER@13.206.238.144:/home/ubuntu
                    ssh -i "$KEY" -o StrictHostKeyChecking=no $USER@13.206.238.144 'sudo mv /home/ubuntu/artisantek-app.war /opt/tomcat/webapps'
                    '''
                }
            }
        }
    }
}
